---

lambda_runtime_docker_image_python: 'public.ecr.aws/lambda/python:3.10'
update_non_pinned_deps: true
lambda_layers_to_pin: []
uv_groups_without:
  - 'dev'
  - 'from-lambda-layers'
  - 'runtime'
  - 'types'
  - 'test'
  - 'tests'
uv_groups_with: []
uv_groups_only: []
strict: true
