---

lambda_runtime_docker_image_python: 'public.ecr.aws/lambda/python:3.10'
update_non_pinned_deps: true
lambda_layers_to_pin: []
poetry_without:
  - 'dev'
  - 'from_lambda_layers'
  - 'runtime'
  - 'types'
  - 'test'
  - 'tests'
poetry_with: []
poetry_only: []
