---

# ------------------
# general settings for the RDS instance
software_component: ''
ssmkey_rds_master_username_key: '/{{ project_id }}/{{ software_component }}/rds/master-username'
rds_endpoint_cloudformation_export_name: ''
rds_endpoint: ''
rds_db_name: '{{ project_id }}'
rds_schema_name: '{{ rds_db_name }}'
rds_port: '5432'

# ------------------
# application user specific settings
app_db_username: ''
ssmkey_rds_app_user_username_key: ''

# ------------------
# DB privileges
privileges: 'connect_only'
