---

- name: 'get default Route53 zone id if needed'
  when: route53_zone_id is not defined or route53_zone_id == ''
  block:
    - name: 'get Route53 stack'
      ringier.aws_cicd.gather_stack_outputs:
        stack_name: '{{ env }}-{{ project_id }}-route53'
        region: '{{ route53_region }}'
      register: route53_stack
    - name: 'get public hosted zone from Route53'
      set_fact:
        route53_zone_id: '{{ route53_stack.outputs.PublicHostedZoneId }}'

- name: 'wait a moment for the validation record'
  pause:
    seconds: 15

- name: 'get ACM validation DNS name and value'
  shell: >-
    aws --region {{ acm_region }} acm describe-certificate  \
      --certificate-arn {{ acm_arn }}  \
      --query 'Certificate.DomainValidationOptions[0].ResourceRecord'  \
      --output json  \
    | jq -crM '.Name, .Value '
  register: acm_validation_resource_record_set_details

- name: 'extract DNS details'
  set_fact:
    acm_dns_name: '{{ acm_validation_resource_record_set_details.stdout_lines[0] }}'
    acm_dns_value: '{{ acm_validation_resource_record_set_details.stdout_lines[1] }}'

- name: 'getting current Route53 validation records'
  command: >-
    aws --region {{ route53_region }} route53 list-resource-record-sets  \
      --hosted-zone-id {{ route53_zone_id }}  \
      --query 'ResourceRecordSets[?Name==`{{ acm_dns_name }}`].ResourceRecords[].Value'  \
      --output text  \
      --no-paginate
  register: result

- name: 'evaluating if Route53 records needs to be created'
  set_fact:
    should_create_route53_record: '{{ acm_dns_value not in result.stdout }}'

- when: should_create_route53_record
  block:
    - name: 'get ACM validation DNS name and value'
      shell: >-
        aws --region {{ acm_region }} acm describe-certificate  \
          --certificate-arn {{ acm_arn }}  \
          --query 'Certificate.DomainValidationOptions[0].ResourceRecord'  \
          --output json  \
        | jq -crM '{ Name: .Name, TTL: 300, Type: .Type, ResourceRecords: [ {Value: .Value}] }'
      register: acm_validation_resource_record_set
    - name: 'creating Route53 record-set for ACM DNS validation'
      command: >-
        aws --region {{ route53_region }} route53 change-resource-record-sets  \
          --query 'ChangeInfo.Id'  \
          --hosted-zone-id {{ route53_zone_id }}  \
          --output text  \
          --change-batch '
          {
            "Comment": "Delete ACM validation record",
            "Changes": [
                {
                    "Action": "CREATE",
                    "ResourceRecordSet": {{ acm_validation_resource_record_set.stdout }}
                }
            ]
          }'
      register: result
    - name: 'wait for Route53 record-set creation'
      command: >-
        aws --region {{ route53_region }} route53 wait resource-record-sets-changed  \
          --id {{ result.stdout }}

- name: 'wait for ACM certificate validation'
  command: >-
    aws --region {{ acm_region }} acm wait certificate-validated   \
      --certificate-arn {{ acm_arn }}
