---

- name: 'check the common variables'
  include_tasks: '{{ role_path }}/../../tasks/validate-common-vars.yml'

- fail:
    msg: "missing var 'environment_var'"
  when: environment_var is not defined or environment_var == ''

- name: try to get the current value of the SSM parameter
  set_fact:
    current_param_value: "{{ lookup('aws_ssm', name, decrypt=true, region=aws_region) }}"
  no_log: true

- name: get the value from the environment variable if available
  set_fact:
    new_param_value: "{{ lookup('env', environment_var) }}"
  no_log: true

- name: guard - make sure that either the existing value is not empty or a new value is provided
  fail:
    msg: 'unable to retrieve the SSM parameter {{ name }}, please provide the environment var {{ environment_var }}'
  when: current_param_value == '' and new_param_value == ''

# use AWS cli instead of Ansible module, because the latter does not support AWS resource tagging
- name: update the value to the SSM parameter store
  command: >-
    aws ssm --region '{{ aws_region }}' put-parameter \
      --name '{{ name }}' \
      --description '{{ description }}' \
      --value '{{ new_param_value }}' \
      --type SecureString \
      --tier Standard \
      --tags Key=Name,Value='{{ name }}'  \
             Key=Project,Value='{{ project_id }}'  \
             Key=Environment,Value='{{ env }}'  \
             Key=Repository,Value='{{ git_info.repo_name }}'  \
             Key=Version,Value='{{ project_version }}'
  when: current_param_value != new_param_value
