---

- name: 'get the absolute path of source dir'
  set_fact:
    source_dir: '{{ (playbook_dir, "../app") | path_join | realpath }}'
  when: source_path is not defined or source_path == ''

- name: 'get default source dir if not specified'
  set_fact:
    source_dir: '{{ source_path | realpath }}'
  when: source_path is defined and source_path != ''

- name: 'check if pyproject.toml exists'
  stat:
    path: '{{ source_dir }}/pyproject.toml'
  register: r_stat
  changed_when: False
  failed_when: not r_stat.stat.exists
  no_log: true

- name: 'check if uv.lock exists'
  stat:
    path: '{{ source_dir }}/uv.lock'
  register: r_stat
  changed_when: False
  failed_when: not r_stat.stat.exists
  no_log: true

- name: 'check if the runtime group exists in pyproject.toml'
  shell: >
    cd "{{ source_dir }}"
    grep -q "^\[dependency-groups\.runtime\]" pyproject.toml || grep -q "^\[tool\.uv\.groups\.runtime\]" pyproject.toml
  register: r_uv_runtime_check
  changed_when: False
  failed_when: r_uv_runtime_check.rc != 0

- name: 'is pyproject.toml up-to-date?'
  when: lambda_layers_to_pin is defined and lambda_layers_to_pin | length > 0
  block:
    - name: 'create tmp folder'
      ansible.builtin.file:
        path: '{{ workspace_path }}/tmp'
        state: 'directory'
      changed_when: False
    - name: 'copy update_project.sh to tmp dir and make it executable'
      ansible.builtin.copy:
        src: '{{ role_path }}/files/update_project.sh'
        dest: '{{ workspace_path }}/tmp/update_project.sh'
        mode: 'u+x'
    - name: 'update pyproject.toml'
      ansible.builtin.shell: '{{ workspace_path }}/tmp/update_project.sh "{{ update_non_pinned_deps | lower }}" "{{ lambda_layers_to_pin | join(" ") }}"'
      args:
        chdir: '{{ source_dir }}'
    - name: 'fail if uv.lock has changed in git (allow just comments to change)'
      shell: |
        cd "{{ source_dir }}"
        git diff --exit-code -G'^[^#]' uv.lock
      register: r_git_diff
      failed_when: r_git_diff.rc != 0
      changed_when: False
      no_log: false

- name: 'gather Ansible facts'
  # we need only the current time with millisecond precision, but Ansible does not offer an option to specify, we have to get all
  gather_facts: {}

- name: 'compute the output dir path'
  set_fact:
    output_dir: '{{ workspace_path }}/lambda_{{ ansible_date_time.iso8601_micro| hash("md5") }}'
    intermediate_dir: '{{ workspace_path }}/lambda_{{ ansible_date_time.iso8601_micro| hash("md5") }}.tmp'

- name: 'create the intermediate dir'
  file:
    path: '{{ intermediate_dir }}'
    state: 'directory'
  changed_when: False

- name: 'delete the output dir to absolutely clear the content'
  file:
    path: '{{ output_dir }}'
    state: 'absent'
  changed_when: False

- name: 'create the output dir'
  file:
    path: '{{ output_dir }}'
    state: 'directory'
  changed_when: False

- name: 'prepare the source files for the container'
  ansible.posix.synchronize:
    src: '{{ source_dir }}/'
    dest: '{{ intermediate_dir }}'
    copy_links: yes
    recursive: yes
    delete: yes
    rsync_opts:
      - '--exclude=tests'
      - '--exclude=__pycache__'
      - '--exclude=.pytest_cache'
      - '--exclude=.coverage'
      - '--exclude=coverage'
      - '--exclude=dist'
      - '--exclude=.venv'
      - '--exclude=venv'
      - '--exclude=.mypy_cache'
  no_log: '{{ ansible_verbosity < 3 }}'

- name: 'place the shell script to be executed inside the container'
  copy:
    src: '{{ role_path }}/files/docker_build_python.sh'
    dest: '{{ intermediate_dir }}/docker_build_python.sh'
    mode: 0755

- name: 'pull the docker image for lambda runtime'
  command: >
    docker pull {{ lambda_runtime_docker_image_python }}

- name: 'get pyproject.toml dependency groups'
  shell: >
    cd "{{ source_dir }}" && 
    (grep -E '^\[dependency-groups\.[^]]+\]' pyproject.toml | sed -E 's/^\[dependency-groups\.([^]]+)\]$/\1/' || true) &&
    (grep -E '^\[tool\.uv\.groups\.[^]]+\]' pyproject.toml | sed -E 's/^\[tool\.uv\.groups\.([^]]+)\]$/\1/' || true) |
    sort | uniq
  register: r_uv_groups

- name: 'intersect the groups with uv_groups_without'
  set_fact:
    uv_groups_without: '{{ uv_groups_without | default([]) | intersect(r_uv_groups.stdout_lines) }}'
  when: uv_groups_without is defined and uv_groups_without | length > 0

- name: 'intersect the groups with uv_groups_with'
  set_fact:
    uv_groups_with: '{{ uv_groups_with | default([]) | intersect(r_uv_groups.stdout_lines) }}'
  when: uv_groups_with is defined and uv_groups_with | length > 0

- name: 'intersect the groups with uv_groups_only'
  set_fact:
    uv_groups_only: '{{ uv_groups_only | default([]) | intersect(r_uv_groups.stdout_lines) }}'
  when: uv_groups_only is defined and uv_groups_only | length > 0

- name: 'build the app inside lambda runtime container'
  command: >
    docker run --rm
      -v "{{ output_dir }}:/output"
      -v "{{ intermediate_dir }}:/workspace"
      --entrypoint "/workspace/docker_build_python.sh"
      {{ lambda_runtime_docker_image_python }}
      {% if strict %}--strict{% endif %}
      {% if uv_groups_only is defined and uv_groups_only | length > 0 %}--only {{ uv_groups_only | join(',') }}{% endif %}
      {% if uv_groups_without is defined and uv_groups_without | length > 0 %}--without {{ uv_groups_without | join(',') }}{% endif %}
      {% if uv_groups_with is defined and uv_groups_with | length > 0 %}--with {{ uv_groups_with | join(',') }}{% endif %}

- name: 'set output'
  set_fact:
    lambda_code_path: '{{ output_dir }}'
